In [14]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob

In [93]:
# Merging csv files (without repeating header)
interesting_files = glob.glob("raw_data/*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
df.head()

C:\Users\Loba\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... NAS_DELAY  \
0            0.0      54.0  DEN            11292  ...       NaN   
1            0.0     623.0  ORD            13930  ...       NaN   
2           22.0     622.0  LAS            12889  ...       NaN   
3            2.0     912.0  MEM            13244  ...       NaN   
4          213.0    1852.0  LAS            12889  ...       0.0   

  OP_CARRIER_FL_NUM OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0               408                F9     LAX              12892   
1              1286                F9     DEN              11292   
2              1679                F9     MCO              13204   
3              1990                F9     LAS              12889   
4              1999                F9     MEM              13244   

   ORIGIN_CITY_NAME ORIGIN_STATE_NM SECURITY_DELAY  Unnamed: 23 WEATHER_DELAY  
0   Los Angeles, CA      California            NaN          NaN           NaN  
1        Denver, CO        Colorado            NaN          NaN           NaN  
2       Orlando, FL         Florida            NaN          NaN           NaN  
3     Las Vegas, NV          Nevada            NaN          NaN           NaN  
4       Memphis, TN       Tennessee            0.0          NaN           0.0  

[5 rows x 24 columns]

In [16]:
# df = pd.read_csv("../flight_info_2018.csv")

# df.head()


In [17]:
len(df)

7272370

In [18]:
df.count()

ARR_DELAY              7130071
ARR_DELAY_NEW          7130071
ARR_TIME               7148852
CARRIER_DELAY          1400632
DAY_OF_WEEK            7272370
DEP_DELAY              7150656
DEP_DELAY_NEW          7150656
DEP_TIME               7156199
DEST                   7272370
DEST_AIRPORT_ID        7272370
DEST_CITY_NAME         7272370
DEST_STATE_NM          7272370
FL_DATE                7272370
LATE_AIRCRAFT_DELAY    1400632
NAS_DELAY              1400632
OP_CARRIER_FL_NUM      7272370
OP_UNIQUE_CARRIER      7272370
ORIGIN                 7272370
ORIGIN_AIRPORT_ID      7272370
ORIGIN_CITY_NAME       7272370
ORIGIN_STATE_NM        7272370
SECURITY_DELAY         1400632
Unnamed: 23                  0
WEATHER_DELAY          1400632
dtype: int64

In [19]:


# df.OP_UNIQUE_CARRIER(dtype)


old = pd.DataFrame(zip(df.OP_UNIQUE_CARRIER))
old
# old.to_csv("old_carriers")

0
0        F9
1        F9
2        F9
3        F9
4        F9
5        F9
6        F9
7        F9
8        F9
9        F9
10       F9
11       F9
12       F9
13       F9
14       F9
15       F9
16       F9
17       F9
18       F9
19       F9
20       F9
21       F9
22       F9
23       F9
24       F9
25       F9
26       F9
27       F9
28       F9
29       F9
...      ..
7272340  AA
7272341  AA
7272342  AA
7272343  AA
7272344  AA
7272345  AA
7272346  AA
7272347  AA
7272348  AA
7272349  AA
7272350  AA
7272351  AA
7272352  AA
7272353  AA
7272354  AA
7272355  AA
7272356  AA
7272357  AA
7272358  AA
7272359  AA
7272360  AA
7272361  AA
7272362  AA
7272363  AA
7272364  AA
7272365  AA
7272366  AA
7272367  AA
7272368  AA
7272369  AA

[7272370 rows x 1 columns]

In [20]:


print(df['OP_UNIQUE_CARRIER'].unique())


['F9' 'EV' 'G4' 'HA' 'MQ' 'NK' 'OH' 'OO' 'WN' 'YV' 'YX' 'AA' 'AS' 'DL'
 '9E' 'B6' 'UA' 'VX']


In [ ]:
print(df['OP_UNIQUE_CARRIER'].unique())

In [113]:
df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY", "ARR_DELAY", "DEST_AIRPORT_ID"]] = df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY", "ARR_DELAY", "DEST_AIRPORT_ID"]].fillna(value=0)

df.head()


ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... NAS_DELAY  \
0            0.0      54.0  DEN            11292  ...       NaN   
1            0.0     623.0  ORD            13930  ...       NaN   
2           22.0     622.0  LAS            12889  ...       NaN   
3            2.0     912.0  MEM            13244  ...       NaN   
4          213.0    1852.0  LAS            12889  ...       0.0   

  OP_CARRIER_FL_NUM OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0               408                F9     LAX              12892   
1              1286                F9     DEN              11292   
2              1679                F9     MCO              13204   
3              1990                F9     LAS              12889   
4              1999                F9     MEM              13244   

   ORIGIN_CITY_NAME ORIGIN_STATE_NM SECURITY_DELAY  Unnamed: 23 WEATHER_DELAY  
0   Los Angeles, CA      California            NaN          NaN           NaN  
1        Denver, CO        Colorado            NaN          NaN           NaN  
2       Orlando, FL         Florida            NaN          NaN           NaN  
3     Las Vegas, NV          Nevada            NaN          NaN           NaN  
4       Memphis, TN       Tennessee            0.0          NaN           0.0  

[5 rows x 24 columns]

In [112]:
len(df)

7272370

In [114]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dfle = df
dfle.OP_UNIQUE_CARRIER = le.fit_transform(dfle.OP_UNIQUE_CARRIER)

dfle.head()

ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... NAS_DELAY  \
0            0.0      54.0  DEN            11292  ...       NaN   
1            0.0     623.0  ORD            13930  ...       NaN   
2           22.0     622.0  LAS            12889  ...       NaN   
3            2.0     912.0  MEM            13244  ...       NaN   
4          213.0    1852.0  LAS            12889  ...       0.0   

  OP_CARRIER_FL_NUM OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0               408                 6     LAX              12892   
1              1286                 6     DEN              11292   
2              1679                 6     MCO              13204   
3              1990                 6     LAS              12889   
4              1999                 6     MEM              13244   

   ORIGIN_CITY_NAME  ORIGIN_STATE_NM SECURITY_DELAY  Unnamed: 23 WEATHER_DELAY  
0   Los Angeles, CA       California            NaN          NaN           NaN  
1        Denver, CO         Colorado            NaN          NaN           NaN  
2       Orlando, FL          Florida            NaN          NaN           NaN  
3     Las Vegas, NV           Nevada            NaN          NaN           NaN  
4       Memphis, TN        Tennessee            0.0          NaN           0.0  

[5 rows x 24 columns]

In [115]:
#reshaping


X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY", "ARR_DELAY", "DEST_AIRPORT_ID"]]
y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
print(X.shape, y.shape)





(7272370, 7) (7272370, 1)


In [116]:
X = X.round(0).astype(int)
y = y.round(0).astype(int)


In [105]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [141]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.6, random_state=4)



In [148]:
X_test.head()

DAY_OF_WEEK  DEP_TIME  ORIGIN_AIRPORT_ID  OP_CARRIER_FL_NUM  \
219835            3      1718              12892                285   
498141            6      2130              13303               2521   
641101            7       721              12266               6262   
547334            7      2010              14100               1655   
57218             1      2229              13487               2166   

        DEP_DELAY  ARR_DELAY  DEST_AIRPORT_ID  
219835         -7        -24            12982  
498141          0        -15            13930  
641101         -4         -4            14100  
547334         -7        -19            12953  
57218         118        111            15096

In [143]:
y_test[0:10]

array([[ -7],
       [  0],
       [ -4],
       [ -7],
       [118],
       [ 52],
       [ -3],
       [ 37],
       [ -5],
       [ -7]])

In [149]:
# Create a LinearRegression model and fit it to  training data

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

# predictions
# PREDICT DEP_DELAY in minutes

abb_X = X_test[0:10]
predictions = model.predict(abb_X)


predictions = predictions.round(0).astype(int)
predictions

array([[ -7],
       [  0],
       [ -4],
       [ -7],
       [118],
       [ 52],
       [ -3],
       [ 37],
       [ -5],
       [ -7]])

In [150]:
model.intercept_

array([7.2724049e-12])

In [153]:
# Ridge model
# Note: Use an alpha of .01 when creating the model for this activity
from sklearn.linear_model import Ridge

### BEGIN SOLUTION
ridge = Ridge(alpha=.01).fit(X_train, y_train)

predictionsR = ridge.predict(X_test)

predictionsR = predictionsR.round(0).astype(int)
# MSE = mean_squared_error(y_test_scaled, predictions)
# r2 = ridge.score(X_test_scaled, y_test_scaled)
# ### END SOLUTION
predictionsR
# print(f"MSE: {MSE}, R2: {r2}")

array([[-7],
       [ 0],
       [-4],
       ...,
       [-3],
       [ 7],
       [-5]])

In [154]:
from sklearn.metrics import mean_squared_error
# call it with test data
MSE = mean_squared_error(y_test, predictionsR)
r2 = ridge.score(X_test, y_test)
print(f"MSE: {MSE}, R2: {r2}")

MSE: 0.0, R2: 1.0


In [ ]:
model.predict([[1,702,11986,14107,6]])

In [ ]:
model.predict([[1,702,1074,14107,1074,6]])


DAY_OF_WEEK		d --OP_UNIQUE_CARRIER	OP_CARRIER_FL_NUM	ORIGIN_AIRPORT_ID	DEST_AIRPORT_ID	DEST	DEP_TIME	DEP_DELAY
1		AS	1	11278	14747	SEA	757	-3
1	2019-01-07	F9	1074	14107	11986	GRR	702	-8


In [ ]:
X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
model.predict([[1,702,11986,14107,6]])