In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import glob

In [126]:
# Merging csv files (without repeating header)
interesting_files = glob.glob("raw_data/*.csv") 
df = pd.concat((pd.read_csv(f, header = 0) for f in interesting_files))
df

C:\Users\Loba\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  \
0            -1.0            0.0     417.0            NaN            1   
1           -32.0            0.0     933.0            NaN            1   
2             5.0            5.0     824.0            NaN            1   
3             7.0            7.0    1436.0            NaN            1   
4           212.0          212.0    2029.0          210.0            1   
5            89.0           89.0     959.0            0.0            1   
6           125.0          125.0    1334.0            0.0            1   
7           116.0          116.0    1527.0           11.0            1   
8           -22.0            0.0      34.0            NaN            1   
9            -1.0            0.0    1009.0            NaN            1   
10           -4.0            0.0    1336.0            NaN            1   
11           -2.0            0.0    1718.0            NaN            1   
12           10.0           10.0    2012.0            NaN            1   
13           15.0           15.0    2314.0            8.0            1   
14          -10.0            0.0    1409.0            NaN            1   
15          124.0          124.0    1913.0            0.0            1   
16           78.0           78.0    2211.0            0.0            1   
17          -17.0            0.0     814.0            NaN            1   
18          -23.0            0.0    1142.0            NaN            1   
19          198.0          198.0    1922.0          198.0            1   
20          -28.0            0.0    1035.0            NaN            1   
21          -33.0            0.0    1442.0            NaN            1   
22          -32.0            0.0    1849.0            NaN            1   
23          -11.0            0.0    2230.0            NaN            1   
24            5.0            5.0    1103.0            NaN            1   
25          -18.0            0.0    1511.0            NaN            1   
26          -21.0            0.0    2149.0            NaN            1   
27          -26.0            0.0     106.0            NaN            1   
28           13.0           13.0    1133.0            NaN            1   
29          -11.0            0.0    1356.0            NaN            1   
...           ...            ...       ...            ...          ...   
644643       53.0           53.0    2017.0           19.0            7   
644644       15.0           15.0    1939.0            0.0            7   
644645        1.0            1.0    1925.0            NaN            7   
644646       50.0           50.0    1522.0           50.0            7   
644647      -10.0            0.0    1422.0            NaN            7   
644648      102.0          102.0    1614.0          102.0            7   
644649       -8.0            0.0    1427.0            NaN            7   
644650       17.0           17.0    1931.0            0.0            7   
644651      121.0          121.0    2115.0            0.0            7   
644652       66.0           66.0    2020.0            0.0            7   
644653      -12.0            0.0    1902.0            NaN            7   
644654      -16.0            0.0    1048.0            NaN            7   
644655        6.0            6.0    1110.0            NaN            7   
644656      -17.0            0.0    1047.0            NaN            7   
644657       -1.0            0.0    1103.0            NaN            7   
644658        9.0            9.0    1847.0            NaN            7   
644659       14.0           14.0    1852.0            NaN            7   
644660        3.0            3.0    1841.0            NaN            7   
644661      -13.0            0.0    2010.0            NaN            7   
644662        0.0            0.0    2109.0            NaN            7   
644663       40.0           40.0    2149.0            0.0            7   
644664      -11.0            0.0    2058.0            NaN            7   
644665      

In [97]:
# df = pd.read_csv("../flight_info_2018.csv")

# df.head()


In [98]:
len(df)

7272370

In [100]:
df.count()

ARR_DELAY              7130071
ARR_DELAY_NEW          7130071
ARR_TIME               7148852
CARRIER_DELAY          1400632
DAY_OF_WEEK            7272370
DEP_DELAY              7150656
DEP_DELAY_NEW          7150656
DEP_TIME               7156199
DEST                   7272370
DEST_AIRPORT_ID        7272370
DEST_CITY_NAME         7272370
DEST_STATE_NM          7272370
FL_DATE                7272370
LATE_AIRCRAFT_DELAY    1400632
NAS_DELAY              1400632
OP_CARRIER_FL_NUM      7272370
OP_UNIQUE_CARRIER      7272370
ORIGIN                 7272370
ORIGIN_AIRPORT_ID      7272370
ORIGIN_CITY_NAME       7272370
ORIGIN_STATE_NM        7272370
SECURITY_DELAY         1400632
Unnamed: 23                  0
WEATHER_DELAY          1400632
dtype: int64

In [127]:


# df.OP_UNIQUE_CARRIER(dtype)


old = pd.DataFrame(zip(df.OP_UNIQUE_CARRIER))
old
# old.to_csv("old_carriers")

0
0        F9
1        F9
2        F9
3        F9
4        F9
5        F9
6        F9
7        F9
8        F9
9        F9
10       F9
11       F9
12       F9
13       F9
14       F9
15       F9
16       F9
17       F9
18       F9
19       F9
20       F9
21       F9
22       F9
23       F9
24       F9
25       F9
26       F9
27       F9
28       F9
29       F9
...      ..
7272340  AA
7272341  AA
7272342  AA
7272343  AA
7272344  AA
7272345  AA
7272346  AA
7272347  AA
7272348  AA
7272349  AA
7272350  AA
7272351  AA
7272352  AA
7272353  AA
7272354  AA
7272355  AA
7272356  AA
7272357  AA
7272358  AA
7272359  AA
7272360  AA
7272361  AA
7272362  AA
7272363  AA
7272364  AA
7272365  AA
7272366  AA
7272367  AA
7272368  AA
7272369  AA

[7272370 rows x 1 columns]

In [128]:


print(df['OP_UNIQUE_CARRIER'].unique())


['F9' 'EV' 'G4' 'HA' 'MQ' 'NK' 'OH' 'OO' 'WN' 'YV' 'YX' 'AA' 'AS' 'DL'
 '9E' 'B6' 'UA' 'VX']


In [106]:

df.head()
#preview the dataframe
df = df.drop(['Unnamed: 23'], axis=1)
df.head()

ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... LATE_AIRCRAFT_DELAY  \
0            0.0      54.0  DEN            11292  ...                 NaN   
1            0.0     623.0  ORD            13930  ...                 NaN   
2           22.0     622.0  LAS            12889  ...                 NaN   
3            2.0     912.0  MEM            13244  ...                 NaN   
4          213.0    1852.0  LAS            12889  ...                 2.0   

  NAS_DELAY OP_CARRIER_FL_NUM  OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0       NaN               408                 F9     LAX              12892   
1       NaN              1286                 F9     DEN              11292   
2       NaN              1679                 F9     MCO              13204   
3       NaN              1990                 F9     LAS              12889   
4       0.0              1999                 F9     MEM              13244   

  ORIGIN_CITY_NAME ORIGIN_STATE_NM  SECURITY_DELAY WEATHER_DELAY  
0  Los Angeles, CA      California             NaN           NaN  
1       Denver, CO        Colorado             NaN           NaN  
2      Orlando, FL         Florida             NaN           NaN  
3    Las Vegas, NV          Nevada             NaN           NaN  
4      Memphis, TN       Tennessee             0.0           0.0  

[5 rows x 23 columns]

In [107]:
#fillna with 0

df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY"]] =  df[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "DEP_DELAY"]].fillna(value=0)



df.head()

ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... LATE_AIRCRAFT_DELAY  \
0            0.0      54.0  DEN            11292  ...                 NaN   
1            0.0     623.0  ORD            13930  ...                 NaN   
2           22.0     622.0  LAS            12889  ...                 NaN   
3            2.0     912.0  MEM            13244  ...                 NaN   
4          213.0    1852.0  LAS            12889  ...                 2.0   

  NAS_DELAY OP_CARRIER_FL_NUM  OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0       NaN               408                 F9     LAX              12892   
1       NaN              1286                 F9     DEN              11292   
2       NaN              1679                 F9     MCO              13204   
3       NaN              1990                 F9     LAS              12889   
4       0.0              1999                 F9     MEM              13244   

  ORIGIN_CITY_NAME ORIGIN_STATE_NM  SECURITY_DELAY WEATHER_DELAY  
0  Los Angeles, CA      California             NaN           NaN  
1       Denver, CO        Colorado             NaN           NaN  
2      Orlando, FL         Florida             NaN           NaN  
3    Las Vegas, NV          Nevada             NaN           NaN  
4      Memphis, TN       Tennessee             0.0           0.0  

[5 rows x 23 columns]

In [79]:
len(df)

7272370

In [108]:
#reshaping

X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
print(X.shape, y.shape)





(7272370, 5) (7272370, 1)


In [109]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
dfle = df
dfle.OP_UNIQUE_CARRIER = le.fit_transform(dfle.OP_UNIQUE_CARRIER)

dfle.head()

ARR_DELAY  ARR_DELAY_NEW  ARR_TIME  CARRIER_DELAY  DAY_OF_WEEK  DEP_DELAY  \
0       -1.0            0.0     417.0            NaN            1       -1.0   
1      -32.0            0.0     933.0            NaN            1       -7.0   
2        5.0            5.0     824.0            NaN            1       22.0   
3        7.0            7.0    1436.0            NaN            1        2.0   
4      212.0          212.0    2029.0          210.0            1      213.0   

   DEP_DELAY_NEW  DEP_TIME DEST  DEST_AIRPORT_ID  ... LATE_AIRCRAFT_DELAY  \
0            0.0      54.0  DEN            11292  ...                 NaN   
1            0.0     623.0  ORD            13930  ...                 NaN   
2           22.0     622.0  LAS            12889  ...                 NaN   
3            2.0     912.0  MEM            13244  ...                 NaN   
4          213.0    1852.0  LAS            12889  ...                 2.0   

  NAS_DELAY OP_CARRIER_FL_NUM  OP_UNIQUE_CARRIER  ORIGIN  ORIGIN_AIRPORT_ID  \
0       NaN               408                  6     LAX              12892   
1       NaN              1286                  6     DEN              11292   
2       NaN              1679                  6     MCO              13204   
3       NaN              1990                  6     LAS              12889   
4       0.0              1999                  6     MEM              13244   

   ORIGIN_CITY_NAME ORIGIN_STATE_NM  SECURITY_DELAY WEATHER_DELAY  
0   Los Angeles, CA      California             NaN           NaN  
1        Denver, CO        Colorado             NaN           NaN  
2       Orlando, FL         Florida             NaN           NaN  
3     Las Vegas, NV          Nevada             NaN           NaN  
4       Memphis, TN       Tennessee             0.0           0.0  

[5 rows x 23 columns]

In [130]:
print(dfle['OP_UNIQUE_CARRIER'].unique())

[ 6  5  7  8  9 10 11 12 15 16 17  1  2  4  0  3 13 14]


In [111]:
#reshaping

X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
print(X.shape, y.shape)


(7272370, 5) (7272370, 1)


In [112]:
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression

In [113]:
# Split the data into training and testing

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)



In [115]:
X_test

DAY_OF_WEEK  DEP_TIME  ORIGIN_AIRPORT_ID  OP_CARRIER_FL_NUM  \
236666            3    1954.0              10821                301   
408419            5     832.0              13303               2537   
85932             1    1430.0              12451               2342   
393447            5    1511.0              10397               2591   
93571             2    1844.0              15016                 18   
68433             1    1138.0              15919               3604   
439718            6    1414.0              12892               1257   
333012            4     649.0              13487               4746   
553869            6    1159.0              13198               2812   
33926             1    1620.0              11298               2418   
469162            6     715.0              13796               6419   
432565            6    2014.0              14492               5281   
100001            2    1139.0              11252                500   
481573            6    1910.0              13796               4927   
52681             1    1840.0              11298               2408   
229485            3    1239.0              12953               3347   
338300            4    2046.0              10821               1233   
98599             1    1658.0              13796               3522   
201860            3     614.0              12889               1009   
89684             2    1907.0              12451               3485   
265077            3    1709.0              11278               5180   
237626            3    1903.0              11259                173   
228693            3    1905.0              10397               1777   
440947            5    1958.0              12953                556   
136532            2    1126.0              15412               3139   
613880            7     804.0              11292                598   
454740            6    1427.0              13061               3941   
251085            4    1152.0              10980               3521   
107639            2    2157.0              14869               7397   
142203            2    2225.0              10821               5467   
...             ...       ...                ...                ...   
473781            6    1743.0              11775               5835   
104400            2     745.0              15304               1369   
25803             1    1744.0              10792                295   
12899             1    2310.0              14747                660   
248942            4     658.0              10693               2297   
219445            3    1444.0              11057               5104   
379559            4    2028.0              13930               3053   
320832            4     910.0              10721               5969   
404072            5    2000.0              14635                140   
320904            4     622.0              11697               2777   
365039            5    1931.0              11618                677   
396337            5    1751.0              13930               5066   
157479            2    1844.0              12889                915   
71685             1       0.0              11066                588   
255590            4     756.0              14685               3359   
352882            4     909.0              11298               2521   
249892            3    1914.0              12953                521   
583328            7    1745.0              10397               2496   
92959             2    1613.0              14683               2224   
584146            7    1750.0              11292               3747   
250409            3    2119.0              10397               2284   
353911            5    1146.0              14747               4737   
550905            7    1034.0              13930               5217   
124659            2    1109.0              11292               5123   
505361            6    1135.0   

In [123]:
X_test[0:1000]

DAY_OF_WEEK  DEP_TIME  ORIGIN_AIRPORT_ID  OP_CARRIER_FL_NUM  \
236666            3    1954.0              10821                301   
408419            5     832.0              13303               2537   
85932             1    1430.0              12451               2342   
393447            5    1511.0              10397               2591   
93571             2    1844.0              15016                 18   
68433             1    1138.0              15919               3604   
439718            6    1414.0              12892               1257   
333012            4     649.0              13487               4746   
553869            6    1159.0              13198               2812   
33926             1    1620.0              11298               2418   
469162            6     715.0              13796               6419   
432565            6    2014.0              14492               5281   
100001            2    1139.0              11252                500   
481573            6    1910.0              13796               4927   
52681             1    1840.0              11298               2408   
229485            3    1239.0              12953               3347   
338300            4    2046.0              10821               1233   
98599             1    1658.0              13796               3522   
201860            3     614.0              12889               1009   
89684             2    1907.0              12451               3485   
265077            3    1709.0              11278               5180   
237626            3    1903.0              11259                173   
228693            3    1905.0              10397               1777   
440947            5    1958.0              12953                556   
136532            2    1126.0              15412               3139   
613880            7     804.0              11292                598   
454740            6    1427.0              13061               3941   
251085            4    1152.0              10980               3521   
107639            2    2157.0              14869               7397   
142203            2    2225.0              10821               5467   
...             ...       ...                ...                ...   
429297            5    1348.0              13930                602   
326723            4    1406.0              11995               1749   
394247            5     841.0              10821                934   
439671            5     525.0              12217               2979   
449078            5     844.0              12953               5893   
293229            4       0.0              12191                282   
526288            6    2124.0              11618               1526   
82607             1    1323.0              14100               4423   
530796            6     706.0              14492                683   
403655            6    1216.0              13296               5502   
450837            5    1858.0              13930               3692   
179398            2    1252.0              14831               1429   
396903            5    2242.0              14679               1334   
282079            4    2011.0              14869               1346   
380721            5    1230.0              10821                324   
202379            3     851.0              13232               1593   
194779            3    1600.0              12889               1357   
86977             1     704.0              14492               1097   
549168            7    1419.0              11697                181   
224182            3    2354.0              14869               2995   
309601            4     935.0              11057               5289   
209351            3    2046.0              13930               3561   
579959            7    1141.0              10693               3929   
347859            5     532.0              14747               1922   
35233             1     651.0   

In [117]:
# Create a LinearRegression model and fit it to  training data

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [119]:


# predictions
# PREDICT DEP_DELAY in minutes

abb_X = X_test[0:10]
predictions = model.predict(abb_X)


predictions

array([[18.32288379],
       [ 4.00512231],
       [12.128618  ],
       [12.71115677],
       [16.45147299],
       [ 8.70641863],
       [10.90813156],
       [ 2.499235  ],
       [ 8.23672039],
       [14.52065543]])

In [120]:



model.coef_

# X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
# y =  dfle[["DEP_DELAY"]].values.reshape(-1, 1)
# print(X.shape, y.shape)


array([[-1.61285738e-01,  1.23154521e-02, -9.23434461e-05,
         1.62476554e-04,  2.22395619e-02]])

In [121]:
model.intercept_

array([-4.64090288])

In [122]:
model.predict([[1,702,11986,14107,6]])

array([[5.16192434]])

In [ ]:
model.predict([[1,702,1074,14107,1074,6]])


DAY_OF_WEEK		d --OP_UNIQUE_CARRIER	OP_CARRIER_FL_NUM	ORIGIN_AIRPORT_ID	DEST_AIRPORT_ID	DEST	DEP_TIME	DEP_DELAY
1		AS	1	11278	14747	SEA	757	-3
1	2019-01-07	F9	1074	14107	11986	GRR	702	-8


In [ ]:
X = dfle[["DAY_OF_WEEK", "DEP_TIME",'ORIGIN_AIRPORT_ID', "OP_CARRIER_FL_NUM", "OP_UNIQUE_CARRIER"]] 
model.predict([[1,702,11986,14107,6]])